"""
Program inputs: ***.dat files generated by PPMS program by Ivan Kindiak.
Program output: Split data files w.r.t. different IV channels in respective subfolders.

Last edited on 2024-02-21 by Swapna Sindhu Mishra.
"""

folderpath = '' #Input file location?
channels = ['Channel_1','Channel_2'] #names of Samples

headers = 40

import numpy as np
import os
import shutil
import glob

os.chdir(folderpath) #change directory to folderpath
files = glob.glob('*.dat') #import filenames with .dat
filecount = len(files) #number of files in folderpath

print(f'The following {filecount} files will be split into channels:')
print(files)

for items in channels:
    shutil.rmtree(items, ignore_errors=True)    
    os.mkdir(items)

for i in range(filecount):
    data_raw = np.loadtxt(files[i], delimiter='\t', skiprows=headers)
    #Select points for background correction
    for j in range(len(channels)):
        data = np.column_stack((data_raw[:,0],data_raw[:,1], data_raw[:,2],data_raw[:,3+j], data_raw[:,6+j]))
        #Save corrected files in subdirectory
        filename = ''.join(files[i].split())[:-4] #remove extra .dat
        filepath = f'{folderpath}/{channels[j]}/{filename}_Ch{j+1}.dat'
        np.savetxt(filepath, data, delimiter='\t')

print("All files were split into channels and saved in respective subfolder.")
